<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 2017/9/14
 * Time: 下午4:30
 */

namespace api\controllers;

use yii;
use yii\rest\Controller;
use yii\filters\ContentNegotiator;
use yii\web\Response;
use yii\base\Exception;

class LoginController extends Controller
{
    public $PostParams;
    public $GetParams;
    public $modelClass = 'app\models\Members';
    public $serializer = [
        'class' => 'yii\rest\Serializer',
        'collectionEnvelope' => 'items',
    ];

    public function behaviors() {
        $behaviors = parent::behaviors();
        $behaviors['contentNegotiator'] = [
            'class' => ContentNegotiator::className(),
            'formats' => [
                'application/json' => Response::FORMAT_JSON,
            ],
        ];
        return $behaviors;
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->PostParams = yii::$app->request->post();
        $this->GetParams  = yii::$app->request->get();
    }

    public function actionIndex()
    {
        try{
            if (!$this->PostParams['username'] || !$this->PostParams['password'])
            {
                throw new Exception('账号或密码不能为空');
            }
            $members = new Members();
            $memberInfo = $members->getMemberInfoByUsername($this->PostParams['username']);

            if (empty($memberInfo))
            {
                throw new Exception('用户不存在');
            }

            if ($memberInfo->validatePassword())
            {
                throw new Exception('密码不正确');
            }

        }catch(Exception $e){

        }
    }
}